"""Scaffold reference-intake assets for a candidate part.

This helper keeps the tracked/private split consistent:

- tracked intake note in ``internal/reference_parts/``
- private raw/derived/scratch folders in ``private/reference_intake/``

Optionally, it copies a provided raw artifact into the candidate's private
``raw/`` folder so the intake pass can start from a stable location.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
INTERNAL_REFERENCE_PARTS = REPO_ROOT / "internal" / "reference_parts"
PRIVATE_REFERENCE_INTAKE = REPO_ROOT / "private" / "reference_intake"


def slug_to_title(slug: str) -> str:
    return slug.replace("-", " ").replace("_", " ").title()


def build_intake_note(
    *,
    title: str,
    family: str,
    candidate_slug: str,
    artifact_type: str,
    artifact_name: str | None,
) -> str:
    artifact_status = artifact_name if artifact_name else "pending concrete reference artifact"
    strength = "pending" if artifact_name is None else "pending classification"
    readiness = "pending concrete artifact" if artifact_name is None else "needs preprocessing"

    return f"""# {title} Intake

## Family

- {family}

## Candidate Part

- proposed normalized part name: `{candidate_slug}`

## Artifact Type

- {artifact_type if artifact_name else artifact_status}

## Artifact Strength

- {strength}

## What The Artifact Clearly Provides

- major envelope dimensions:
  - pending
- interface dimensions:
  - pending
- body-count clues:
  - pending
- relationship or assembly clues:
  - pending

## What The Artifact Does Not Clearly Provide

- missing dimensions:
  - pending
- unclear feature definitions:
  - pending
- tolerance or clearance unknowns:
  - pending

## Derived Working Assets

- raw artifact:
  - {artifact_name or "pending"}
- text extraction:
  - pending
- page images:
  - pending
- cropped views:
  - pending
- table extraction:
  - pending

## Normalization Readiness

- {readiness}

## Notes

- generated by `scripts/scaffold_reference_intake.py`
- do not promote to implementation until this note is filled from a real reference artifact
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Create intake-note and private intake folders for a reference artifact.")
    parser.add_argument("--family-slug", required=True, help="Family folder slug, e.g. enclosures-and-covers")
    parser.add_argument("--family-label", help="Display label for the family field, defaults from slug")
    parser.add_argument("--candidate-slug", required=True, help="Candidate slug, e.g. flanged_junction_box_body")
    parser.add_argument("--display-name", help="Display title for the intake note")
    parser.add_argument(
        "--artifact-type",
        default="pending concrete reference artifact",
        help="Artifact type, e.g. dimensioned PDF drawing",
    )
    parser.add_argument(
        "--source-file",
        help="Optional path to a raw reference artifact to copy into the private raw/ folder",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite an existing intake note if present",
    )
    args = parser.parse_args()

    family_slug = args.family_slug
    family_label = args.family_label or family_slug.replace("-", " ")
    candidate_slug = args.candidate_slug
    display_name = args.display_name or slug_to_title(candidate_slug)

    intake_note_path = INTERNAL_REFERENCE_PARTS / f"intake-{candidate_slug.replace('_', '-')}.md"
    private_base = PRIVATE_REFERENCE_INTAKE / family_slug / candidate_slug
    raw_dir = private_base / "raw"
    derived_dir = private_base / "derived"
    scratch_dir = private_base / "scratch"

    for directory in (raw_dir, derived_dir, scratch_dir):
        directory.mkdir(parents=True, exist_ok=True)

    artifact_name = None
    if args.source_file:
        source_path = Path(args.source_file).expanduser().resolve()
        if not source_path.exists():
            raise SystemExit(f"Source file does not exist: {source_path}")
        destination_path = raw_dir / source_path.name
        shutil.copy2(source_path, destination_path)
        artifact_name = destination_path.name

    if intake_note_path.exists() and not args.force:
        raise SystemExit(f"Intake note already exists: {intake_note_path}. Use --force to overwrite.")

    note = build_intake_note(
        title=display_name,
        family=family_label,
        candidate_slug=candidate_slug,
        artifact_type=args.artifact_type,
        artifact_name=artifact_name,
    )
    intake_note_path.write_text(note, encoding="utf-8")

    print(f"Created intake note: {intake_note_path}")
    print(f"Prepared private folders: {private_base}")
    if artifact_name:
        print(f"Copied raw artifact: {raw_dir / artifact_name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
